name       : eiskaltdcpp
version    : 2.2.10
release    : 2
source     :
    - https://github.com/eiskaltdcpp/eiskaltdcpp/archive/v2.2.10.tar.gz : e461c8c499e459651d6382a6ded6788e5ac9a9c4ff26386c3cf073d94d606127
license    : GPL-3.0
component  : network.clients
summary    : EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols.
description: |
    EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libidn2)
    - pkgconfig(libnotify)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/switch-to-gnu-libidn2.patch
    %cmake -DUSE_QT=0 -DUSE_GTK3=1 \
           -DLIBDIR=lib64 \
           -DPERL_REGEX=1 \
           -DFREE_SPACE_BAR_C=0 \
           .
build      : |
    %make
install    : |
    %make_install
