name       : eiskaltdcpp
version    : 2.2.10
release    : 7
source     :
    - git|https://github.com/eiskaltdcpp/eiskaltdcpp.git : 89348ec73bd59ba91abbddaf69390d219dcb8cb3
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : network.clients
summary    : EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols
description: |
    EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libidn2)
    - pkgconfig(libnotify)
    - bzip2-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/switch-to-gnu-libidn2.patch
    %patch -p1 < $pkgfiles/0001-Revert-Core-Refactor-next-protocol-to-a-typed-enum.patch
    %cmake \
        -DFREE_SPACE_BAR_C=OFF \
        -DLIBDIR=lib64 \
        -DLUA_SCRIPT=OFF \
        -DPERL_REGEX=ON \
        -DUSE_GTK3=ON \
        -DUSE_QT=OFF \
        -DUSE_QT5=OFF \
        -DUSE_MINIUPNP=OFF .
build      : |
    %make
install    : |
    %make_install
