name       : eiskaltdcpp
version    : 2.4.2
release    : 10
source     :
    - https://github.com/eiskaltdcpp/eiskaltdcpp/archive/refs/tags/v2.4.2.tar.gz : 2ed853a57c57aab0e87fdea273a01707184ee425a2aaf9fcd2e0a32c57a2de2c
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : network.clients
summary    : EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols
description: |
    EiskaltDC++ is a cross-platform program that uses the Direct Connect and ADC protocols.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libidn2)
    - pkgconfig(lua)
    - pkgconfig(miniupnpc)
    - pkgconfig(x11)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/switch-to-gnu-libidn2.patch
    %cmake_ninja \
        -DLIBDIR=lib64 \
        -DUSE_ASPELL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
